### PR TITLE
Move all sysadmin files to a new `sysadmin` folder

### PR DESCRIPTION
**Pull request by santisoler**

### CODE REVIEW

**Comment by santisoler** [comment]
I think this move of files will help organizing the repo, specially after I opened #2. @jokva let me know what do you think.

**Comment by jokva** [comment]
I'm not sure if this makes any sense (or difference) at all, considering the context of this tree. What do you imagine we'll put here that is _not_ specifically operational stuff which warrants the extra dir?

**Comment by santisoler** [comment]
I don't think we'll add much more stuff here, but I thought it made sense since we are going to point non-maintainers to this repo to read the Getting Started section in the `README.md`. It might be confusing seeing all those files, but maybe I'm being too cautious here.

**Comment by jokva** [comment]
I don't think it is a problem for getting-started (which could maybe be at a swung web site anyway). I propose we close this.

**Comment by santisoler** [comment]
I agree, I would like it to be more visible than this repo. But it was the easiest way for me to get it online (git was just at my finger tips haha). Thanks for closing it @jokva.

**Pull request closed without merging**
