### PR TITLE
Add README.md

### PR DESCRIPTION
**Pull request by santisoler**
Add a `README.md` file with some descriptions of the repository and instructions for getting started with Mattermost. Added some screenshots to help users exploring channels and setting up the Mattermost apps.

### CODE REVIEW

**Comment by santisoler** [comment]
@prisae would you like to take a look at this?

**Comment by jokva** [comment]
I'm perfectly happy with this.

**Comment by prisae** [comment]
LGTM. Small detail, I find the "Browse channel" more intuitively accessed through the big + at the top rather than through the "Add channels" button.

**Comment by santisoler** [comment]
> LGTM. Small detail, I find the "Browse channel" more intuitively accessed through the big + at the top rather than through the "Add channels" button.

You're right! I've always used the "Add channels", but the plus button makes more sense, and it has more options. I'll change that.

**Comment by santisoler** [comment]
I'm merging this. Thanks for the feedback!

**Pull request merged**
