### PR TITLE
Version control the authorized_keys for root

### PR DESCRIPTION
**Pull request by santisoler**
Add `root/.ssh/authorized_keys` file with @jokva and @santisoler ssh
keys. Edit `init.sh` to copy and stow the `root` directory.

### CODE REVIEW

**Comment by santisoler** [comment]
@jokva could you take a look at this and merge if you agree with the changes?

**Comment by jokva** [comment]
Do we even need the -d root check? Since both the script and tree are tracked there is no reason it should not exist.

**Comment by jokva** [comment]
That being said, I suspect that the stow /root is buggy as the directory probably exists already. I think the correct package to stow would be something like -t root .ssh

**Comment by jokva** [comment]
So I just tested this. The right invocation would be:

```
stow -d /stow -t /root root
```
which creates  /root/.ssh -> ../stow/root/.ssh

However, /root/.ssh is already created by the hetzner init so it must be cleared first, probably with `rm -rf /root/.ssh`. This also means that if someone runs init.sh after creating a new image using their own ssh key, they will be *locked out* unless their key is also in $repo/root. I think that is acceptable.

**Comment by santisoler** [comment]
Considering that the stow is not the best option, and replacing the `.ssh/authorized_keys` could potentially lock users out. What if we just append the public keys into the existing file?

```bash
cat root/.ssh/authorized_keys >> /root/.ssh/authorized_keys
```

**Comment by jokva** [comment]
I'm not too worried about locking users out necessarily. This will only happen when init is ran (which is only when creating new parallel instances or wiping and resetting the live one AND that is done by someone that isn't already in the .ssh file (why?). It can be fixed by him just adding himself to authorized_keys and repeating the process, which now won't be a big deal because the instance is fresh anyway.

Appending could be fine, of course, but is less (purity wise) repeatable and is now different from the rest of the init.

**Comment by santisoler** [comment]
Agreed. Then I'll modify the stow line with your previous amendment, and remove the check for the root directory existence.

**Comment by jokva** [comment]
Actually, for the symmetry it would be better to just kill authorized_keys, and then do

```
stow -d /stow/root -t /root/.ssh .ssh

authorized_keys -> ../../stow/root/.ssh/authorized_keys
```

**Comment by jokva** [comment]
https://github.com/softwareunderground/mattermost/commit/5d9aebcb50b4855ab5b3f747db3c55da28c13f3d

Thanks

**Pull request closed without merging**
